baseURL: https://aafu.pages.dev/
languageCode: en-us
publishDir: "docs"
build:
  writeStats: true
params:
  #title: aafu theme
  #author: Darshan Baral
  description: Website title
  copyright: >-
    powered by [hugo](https://gohugo.io/) & deployed on
    [Github pages](https://pages.github.com/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Stephenson Petit-Homme"
    tagline: Java Backend Engineer
    location: "Miami, FL"
    photo: sonson.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "#"
        title: LinkedIn
      # - icon: fab fa-stack-overflow
      #   url: "#"
      #   title: StackOverflow
      - icon: fab fa-github
        url: "https://github.com/speti008"
        title: GitHub
      # - icon: fab fa-twitter
      #   url: "#"
      #   title: Twitter
      # - icon: fab fa-orcid
      #   url: "#"
      #   title: Orcid
      # - icon: ai ai-google-scholar
      #   url: "#"
      #   title: Google Scholar
      # - icon: fab fa-researchgate
      #   url: "#"
      #   title: ResearchGate
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: I’m a Java Backend Engineer with strong experience in building scalable applications using Java and Spring Framework.
                 I am passionate about solving complex problems and continuously improving my craft.
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Java Backend Engineer
        dates: 2020 - *Present* 
        company: Ultimate Software
        details: |1-
          - Designing, building and maintaining the backend system that supports the core functionalities of Ultipro.( a SaaS HCM)
          - Design RESTFUL APIs and microservices, using Spring Boot and Spring Data JPA, that allow the front-end to interact with the database and other backend components.
          - Design and maintain the database schema for handling large volumes of HR-related data, such as employee records. This often involves efficient SQL queries, working with relational databases like MySQL and NoSQL databases like MongoDB.
          - Implement role-based access control(RBAC) to ensure that only authorized users can access sensitive information about employees.
          - Implemented secure authentication using OAuth2 and JWT
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: BS. in Computer Science
        college: Florida International University
        dates: 2012 - 2016
        # thesis_title: "Effect of humans on other humans: a study of human behavior."
        # thesis_url: "#"
      # - degree: M.S. in Subject
        # college: University of State-City
        # dates: 2013 - 2018
        # thesis_title: "Effect of humans on other humans: a study of human behavior."
        # thesis_url: "#"
      # - degree: B.S. in Subject
        # college: University of State-City
        # dates: 2004 - 2009
  # publication:
  #   title: Publications
  #   icon: fas fa-book
  #   format:
  #     - date
  #     - title
  #     - authors
  #     - journal
  #   types:
  #     - Journal Articles
  #     - Proceedings
  #   list:
  #     - title: >-
  #         Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
  #         eiusmod tempor incididunt ut labore et dolore magna aliqua.
  #       authors: "F Last, F Second, P secondary"
  #       date: "2018"
  #       journal: "Journal of Field 52 (16), 9033-9044"
  #       url: "#"
  #       type: Journal Articles
  #     - title: >-
  #         Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
  #         eiusmod tempor incididunt ut labore et dolore magna aliqua.
  #       authors: "F Last, F Second, P secondary"
  #       date: "2018"
  #       journal: "Journal of Field 52 (16), 9033-9044"
  #       url: "#"
  #       type: Journal Articles
  #     - title: >-
  #         Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
  #         eiusmod tempor incididunt ut labore et dolore magna aliqua.
  #       authors: "F Last, F Second, P secondary"
  #       date: "2018"
  #       journal: "Journal of Field 52 (16), 9033-9044"
  #       url: "#"
  #       type: Proceedings
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: Sring Boot CRUD
        url: "https://www.google.com/"
        description: A RBAC Java Spring + Tymeleaf program that execute simple CRUD operations. 
                     Flyway is used as a database migration tool to handle changes in the database schema.
                     And Google Faker is used to generate random people's name,gender,birthday and email adress.
                     The full project can be accessed on [Github](https://github.com/speti008/Spring_CRUD) and a live 
                     version [here](https://the-next-image-latest.onrender.com/login).
                    
                     
      # - title: Project 2
      #   url: "#"
      #   description: Description of the project
      # - title: Project 3
      #   url: "#"
      #   description: Description of the project
      # - title: Project 4
      #   url: "#"
      #   description: Description of the project
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: Core Java
        skillrating: 80
      - skill: SQL & Relational Database
        skillrating: 75
      - skill: Python
        skillrating: 45
      - skill: Software Engineering & System Design 
        skillrating: 75
      - skill: Git & Github
        skillrating: 80
      - skill: Design Pattern
        skillrating: 70
      - skill: Spring & Spring Boot
        skillrating: 60 
      - skill: Hibernate, JPA & ORM
        skillrating: 60
      - skill: Machine Learning
        skillrating: 45
      - skill: Neural Network
        skillrating: 30
  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: Coding
      - hobby: Reading
      - hobby: Gym
      - hobby: Basketball & Soccer
